import Head from 'next/head'
import Image from 'next/image'
import Title from '../components/Title'
import Footer from "../components/Footer";
import Slider from "../components/Slider";

export default function Home() {

    const user = {
        id : 1,
        email : "vincentbeaudraps@outlook.fr",
        name : "Vincent",
        isAdmin: true
    }

    return (
    <div >
      <Head>
        <title>NextBox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
<Title name={user.name}/>
<Title name={user.email}/>
<Title name={user.id}/>
          <Footer></Footer>
          <Slider></Slider>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
            Explored by Vincent {' '}
        </a>
      </footer>
    </div>
  )
}
